### ISSUE TITLE
Production stability

### ISSUE THREAD

**Issue by nikhilRP** [Network-of-BioThings/myvariant.info#3]
Hi,

Great work with variant info project.
Infact I was part of the hackathon where you guys came up with this.

I am wondering how stable is this now and what are your future plans.
Any plans integrating with mygene.info or making more stable service on its own?

Thanks,
Nikhil

**Comment by newgene** [comment]
Hi Nikhil,

         We are now providing variant annotation services at [MyVariant.info](http://myvariant.info). Since the 1st Nob Hackathon, we have included a lot more variant annotations. v1 API is currently provided, and can be considered stable.

         We are currently working on the automated data source updating pipeline, and also expanding our data source coverage as we go.

Thanks and let us know any feedback,

Chunlei

**Comment by nikhilRP** [comment]
@newgene - Thank you so much.
Will test the new API :)
